import { IRowContext } from 'types/row-context.type';
import { TableColumn } from 'types/table-column.type';
import { VNode } from 'vue';
import { Vue } from 'vue-property-decorator';
export declare type TreeStatus = 'collapsed' | 'expanded' | 'loading' | 'disabled';
export default class DataTableBodyCellComponent extends Vue {
    column: TableColumn;
    rowContext: IRowContext;
    tabIndex: string;
    cellSlot: (obj: Record<string, unknown>) => VNode[];
    renderTracking: boolean;
    displayCheck: (row: Record<string, unknown>, column?: TableColumn, value?: unknown) => boolean;
    sanitizedValue: string;
    value: unknown;
    isFocused: boolean;
    onRowChanged(): void;
    created(): void;
    beforeUpdate(): void;
    checkValueUpdates(): void;
    stripHtml(html: string): string;
    onFocus(): void;
    onBlur(): void;
    onClick(event: MouseEvent): void;
    onDblClick(event: MouseEvent): void;
    onKeyDown(event: KeyboardEvent): void;
    onCheckboxChange(event: MouseEvent): void;
    onTreeAction(event: MouseEvent): void;
    onMouseEnter(event: MouseEvent): void;
    get cssClasses(): Record<string, boolean>;
    get styles(): Record<string, string | number>;
    get marginCellStyle(): Record<string, string>;
    get isCheckboxable(): boolean;
    cellHeight(rowHeight: number): string | number;
    calcLeftMargin(column: TableColumn, row: Record<string, unknown>): number;
}
